version: '2'
services:
  dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: make dev

  tdd:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: make tdd

